apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8-deployment
  namespace: default
  labels:
    app: node-k8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-k8
  template:
    metadata:
      labels:
        app: node-k8
    spec:
      containers:
        - name: node-k8
          image: janikavya23382/node:latest
          ports:
            - containerPort: 3000

          env:
            - name: HOST_URL
              valueFrom:
                secretKeyRef:
                  name: node-app-secrets
                  key: HOST_URL